export const INITIAL_CATEGORIES = [
  { id: 1, name: 'Mobiles & Smartphones', slug: 'mobiles' },
  { id: 2, name: 'Fashion & Apparel', slug: 'fashion' },
  { id: 3, name: 'Electronics', slug: 'electronics' },
  { id: 4, name: 'Audio', slug: 'audio' },
  { id: 5, name: 'Home & Living', slug: 'home-living' },
  { id: 6, name: 'Accessories', slug: 'accessories' }
];

export const INITIAL_PRODUCTS = [
  // --- MOBILIES & SMARTPHONES ---
  {
    id: 1,
    title: 'Apple iPhone 15 Pro Max (256 GB) - Natural Titanium',
    description: 'Forged in titanium with A17 Pro chip, customizable Action button, 48MP main camera system with 5x Telephoto optical zoom, and Super Retina XDR display.',
    price: 149900,
    original_price: 159900,
    category_id: 1,
    category_name: 'Mobiles & Smartphones',
    category_slug: 'mobiles',
    stock: 12,
    rating: 4.9,
    review_count: 342,
    image_url: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=600&auto=format&fit=crop&q=80',
    badge: 'Flipkart Choice',
    features: ['Titanium Design', 'A17 Pro Chip', '48MP Pro Camera System', 'USB-C with USB 3 Speeds']
  },
  {
    id: 2,
    title: 'Samsung Galaxy S24 Ultra 5G (Titanium Gray, 12GB, 512GB)',
    description: 'Galaxy AI is here. 200MP camera with AI Zoom, built-in S Pen, Snapdragon 8 Gen 3 for Galaxy, and quad HD+ Dynamic AMOLED 2X display.',
    price: 129999,
    original_price: 139999,
    category_id: 1,
    category_name: 'Mobiles & Smartphones',
    category_slug: 'mobiles',
    stock: 15,
    rating: 4.8,
    review_count: 289,
    image_url: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=600&auto=format&fit=crop&q=80',
    badge: 'Amazon Bestseller',
    features: ['200MP Quad Camera', 'Built-in S Pen', 'Galaxy AI Features', '5000mAh Battery']
  },
  {
    id: 3,
    title: 'OnePlus 12 5G (Silky Black, 16GB RAM, 512GB Storage)',
    description: 'Powered by Snapdragon 8 Gen 3, 4th Gen Hasselblad Camera System for Mobile, 120Hz ProXDR display with LTPO 3.0, and 100W SUPERVOOC fast charging.',
    price: 64999,
    original_price: 69999,
    category_id: 1,
    category_name: 'Mobiles & Smartphones',
    category_slug: 'mobiles',
    stock: 20,
    rating: 4.7,
    review_count: 198,
    image_url: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=600&auto=format&fit=crop&q=80',
    badge: 'Top Rated',
    features: ['Snapdragon 8 Gen 3', 'Hasselblad Camera', '100W SuperVOOC', '5400mAh Battery']
  },
  {
    id: 4,
    title: 'Google Pixel 8 Pro (Obsidian, 12GB RAM, 128GB)',
    description: 'Google Tensor G3 chip, fully upgraded pro camera system with 5x telephoto, Best Take photo editing, and 24-hour battery life.',
    price: 88999,
    original_price: 106999,
    category_id: 1,
    category_name: 'Mobiles & Smartphones',
    category_slug: 'mobiles',
    stock: 10,
    rating: 4.7,
    review_count: 154,
    image_url: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=600&auto=format&fit=crop&q=80',
    badge: 'AI Special',
    features: ['Tensor G3 AI Chip', 'Best Take Camera Edit', 'Super Actua Display', '7 Years OS Updates']
  },
  {
    id: 5,
    title: 'Xiaomi Redmi Note 13 Pro+ 5G (Fusion Purple, 12GB, 512GB)',
    description: '200MP OIS camera, 3D Curved AMOLED 120Hz display, IP68 dust & water resistance, MediaTek Dimensity 7200-Ultra, and 120W HyperCharge.',
    price: 31999,
    original_price: 35999,
    category_id: 1,
    category_name: 'Mobiles & Smartphones',
    category_slug: 'mobiles',
    stock: 25,
    rating: 4.6,
    review_count: 420,
    image_url: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600&auto=format&fit=crop&q=80',
    badge: 'Hot Deal',
    features: ['200MP OIS Camera', '120W HyperCharge', 'IP68 Water Resistant', '3D Curved AMOLED']
  },
  {
    id: 6,
    title: 'Nothing Phone (2a) 5G (Black, 8GB RAM, 128GB Storage)',
    description: 'Unique transparent design with Glyph Interface lighting, custom Dimensity 7200 Pro 4nm processor, and dual 50MP rear camera setup.',
    price: 23999,
    original_price: 25999,
    category_id: 1,
    category_name: 'Mobiles & Smartphones',
    category_slug: 'mobiles',
    stock: 30,
    rating: 4.6,
    review_count: 512,
    image_url: 'https://images.unsplash.com/photo-1565849904461-04a58ad377e0?w=600&auto=format&fit=crop&q=80',
    badge: 'Popular',
    features: ['Glyph Interface LEDs', '50MP Dual Camera', 'Dimensity 7200 Pro', 'Nothing OS 2.5']
  },

  // --- FASHION & APPAREL ---
  {
    id: 7,
    title: "Levi's Men's 511 Slim Fit Stretchable Denim Jeans (Dark Indigo)",
    description: "Classic 5-pocket styling denim jeans crafted from premium stretchable cotton fabric for maximum flexibility, slim fit silhouette, and modern everyday style.",
    price: 2799,
    original_price: 3999,
    category_id: 2,
    category_name: 'Fashion & Apparel',
    category_slug: 'fashion',
    stock: 22,
    rating: 4.5,
    review_count: 215,
    image_url: 'https://images.unsplash.com/photo-1542272604-780c36856842?w=600&auto=format&fit=crop&q=80',
    badge: '30% OFF',
    features: ['Slim Fit Cut', 'Stretch Denim', 'Zip Fly with Button Closure', 'Machine Washable']
  },
  {
    id: 8,
    title: "Allen Solly Men's Premium Cotton Polo T-Shirt (Navy Blue)",
    description: "Soft breathable 100% combed cotton polo t-shirt with signature embroidered logo on chest, ribbed collar, and stylish contrast side slits.",
    price: 1199,
    original_price: 1699,
    category_id: 2,
    category_name: 'Fashion & Apparel',
    category_slug: 'fashion',
    stock: 40,
    rating: 4.4,
    review_count: 310,
    image_url: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=600&auto=format&fit=crop&q=80',
    badge: 'Fashion Bestseller',
    features: ['100% Combed Cotton', 'Ribbed Collar & Cuffs', 'Regular Fit', 'Breathable Fabric']
  },
  {
    id: 9,
    title: "Puma Men's Smash v2 Leather Sneakers (White & Black)",
    description: "Classic tennis-inspired low boot leather sneakers with comfortable SoftFoam+ sockliner, rubber outsole for traction, and iconic Puma formstrip.",
    price: 2999,
    original_price: 4999,
    category_id: 2,
    category_name: 'Fashion & Apparel',
    category_slug: 'fashion',
    stock: 18,
    rating: 4.7,
    review_count: 180,
    image_url: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=600&auto=format&fit=crop&q=80',
    badge: '40% OFF',
    features: ['SoftFoam+ Cushioning', 'Genuine Leather Upper', 'Durable Rubber Outsole', 'Classic Lace Closure']
  },
  {
    id: 10,
    title: "BIBA Women's Printed Anarkali Kurta & Dupatta Set (Royal Blue)",
    description: "Elegant ethnic floral printed cotton Anarkali kurta set with flared hemline, V-neck, three-quarter sleeves, and matching printed dupatta.",
    price: 3499,
    original_price: 5999,
    category_id: 2,
    category_name: 'Fashion & Apparel',
    category_slug: 'fashion',
    stock: 15,
    rating: 4.8,
    review_count: 95,
    image_url: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600&auto=format&fit=crop&q=80',
    badge: 'Festive Special',
    features: ['Cotton Fabric', 'Anarkali Flare Fit', 'Includes Dupatta', 'Dry Clean Recommended']
  },

  // --- ELECTRONICS & AUDIO ---
  {
    id: 11,
    title: 'Aura ANC Wireless Headphones',
    description: 'Studio-quality wireless over-ear headphones with active noise cancellation, 40-hour battery life, and ultra-soft memory foam ear cushions.',
    price: 14999,
    original_price: 19999,
    category_id: 4,
    category_name: 'Audio',
    category_slug: 'audio',
    stock: 14,
    rating: 4.8,
    review_count: 142,
    image_url: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&auto=format&fit=crop&q=80',
    badge: 'Best Seller',
    features: ['Active Noise Cancellation', '40h Battery Life', 'Bluetooth 5.3', 'Fast USB-C Charging']
  },
  {
    id: 12,
    title: 'Ergonomic Mechanical Keyboard',
    description: 'Compact 75% hot-swappable RGB mechanical keyboard with custom lubricated switches and acoustic dampening foam.',
    price: 8999,
    original_price: 10999,
    category_id: 3,
    category_name: 'Electronics',
    category_slug: 'electronics',
    stock: 8,
    rating: 4.9,
    review_count: 210,
    image_url: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600&auto=format&fit=crop&q=80',
    badge: 'Top Rated',
    features: ['Hot-Swappable PCB', 'South-Facing Per-Key RGB', 'PBT Double-shot Keycaps', 'Triple-Mode Connectivity']
  }
];

export const INITIAL_ORDERS = [
  {
    id: 101,
    order_code: 'ORD-IN8B9C',
    customer_name: 'Sridhar Palivela',
    customer_email: 'sridhar@example.com',
    shipping_address: 'Flat 402, Cyber Towers Road, Madhapur, Hyderabad, Telangana 500081',
    subtotal: 149900,
    discount: 14990,
    tax: 10792,
    total_amount: 145702,
    status: 'Completed',
    created_at: '2026-08-07T14:32:00Z'
  }
];
