export const INITIAL_CATEGORIES = [
  { id: 1, name: 'Electronics', slug: 'electronics' },
  { id: 2, name: 'Audio', slug: 'audio' },
  { id: 3, name: 'Fashion', slug: 'fashion' },
  { id: 4, name: 'Home & Living', slug: 'home-living' },
  { id: 5, name: 'Accessories', slug: 'accessories' }
];

export const INITIAL_PRODUCTS = [
  {
    id: 1,
    title: 'Aura ANC Wireless Headphones',
    description: 'Studio-quality wireless over-ear headphones with active noise cancellation, 40-hour battery life, and ultra-soft memory foam ear cushions for all-day listening comfort.',
    price: 199.99,
    original_price: 249.99,
    category_id: 2,
    category_name: 'Audio',
    category_slug: 'audio',
    stock: 18,
    rating: 4.8,
    review_count: 142,
    image_url: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&auto=format&fit=crop&q=80',
    badge: 'Best Seller',
    features: ['Active Noise Cancellation', '40h Battery Life', 'Bluetooth 5.3', 'Fast USB-C Charging']
  },
  {
    id: 2,
    title: 'Minimalist Leather Smart Watch',
    description: 'Sleek smartwatch featuring a crisp AMOLED display, 24/7 heart rate tracking, sleep monitoring, and a premium genuine Italian leather interchangeable strap.',
    price: 149.50,
    original_price: 180.00,
    category_id: 1,
    category_name: 'Electronics',
    category_slug: 'electronics',
    stock: 12,
    rating: 4.6,
    review_count: 89,
    image_url: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&auto=format&fit=crop&q=80',
    badge: 'Popular',
    features: ['AMOLED Touchscreen', 'Heart Rate & SpO2', '5 ATM Water Resistance', '7-Day Battery']
  },
  {
    id: 3,
    title: 'Ergonomic Mechanical Keyboard',
    description: 'Compact 75% hot-swappable RGB mechanical keyboard with custom lubricated tactile switches and sound dampening foam layers.',
    price: 119.00,
    original_price: 139.00,
    category_id: 1,
    category_name: 'Electronics',
    category_slug: 'electronics',
    stock: 8,
    rating: 4.9,
    review_count: 210,
    image_url: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600&auto=format&fit=crop&q=80',
    badge: 'Top Rated',
    features: ['Hot-Swappable PCB', 'South-Facing Per-Key RGB', 'PBT Double-shot Keycaps', 'Triple-Mode Connectivity']
  },
  {
    id: 4,
    title: 'Vanguard Canvas Travel Backpack',
    description: 'Durable water-resistant canvas backpack with dedicated padded 16-inch laptop sleeve, ergonomic back padding, and quick-access utility pockets.',
    price: 79.99,
    original_price: 99.99,
    category_id: 3,
    category_name: 'Fashion',
    category_slug: 'fashion',
    stock: 25,
    rating: 4.7,
    review_count: 76,
    image_url: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&auto=format&fit=crop&q=80',
    badge: null,
    features: ['Water-Resistant Canvas', '16" Laptop Sleeve', 'Hidden Anti-Theft Pocket', 'Luggage Pass-Through']
  },
  {
    id: 5,
    title: 'Pulse Bass Waterproof Speaker',
    description: 'Rugged portable Bluetooth speaker delivering 360-degree room-filling audio, IPX7 waterproof certification, and integrated speakerphone capabilities.',
    price: 64.99,
    original_price: 79.99,
    category_id: 2,
    category_name: 'Audio',
    category_slug: 'audio',
    stock: 30,
    rating: 4.5,
    review_count: 115,
    image_url: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=600&auto=format&fit=crop&q=80',
    badge: 'Sale',
    features: ['IPX7 Waterproof', '20W Bass Driver', '20h Playtime', 'TWS Stereo Pairing']
  },
  {
    id: 6,
    title: 'Nordic Ceramic Coffee Mug Set',
    description: 'Handcrafted matte finish ceramic coffee mugs (Set of 4), designed with Scandinavian minimalist lines and heat-insulated handles.',
    price: 34.50,
    original_price: 42.00,
    category_id: 4,
    category_name: 'Home & Living',
    category_slug: 'home-living',
    stock: 15,
    rating: 4.6,
    review_count: 53,
    image_url: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=600&auto=format&fit=crop&q=80',
    badge: null,
    features: ['Dishwasher Safe', 'Microwave Safe', 'Lead-Free Ceramic', '350ml Capacity']
  },
  {
    id: 7,
    title: 'Ultra-Slim Wireless Power Bank',
    description: '10,000mAh ultra-slim magnetic power bank with 15W wireless fast-charging and 20W USB-C Power Delivery output.',
    price: 49.99,
    original_price: 59.99,
    category_id: 1,
    category_name: 'Electronics',
    category_slug: 'electronics',
    stock: 4,
    rating: 4.4,
    review_count: 98,
    image_url: 'https://images.unsplash.com/photo-1609592424074-1296c5689100?w=600&auto=format&fit=crop&q=80',
    badge: 'Low Stock',
    features: ['10000mAh Capacity', '15W MagSafe Wireless', '20W USB-C PD', 'LED Battery Indicator']
  },
  {
    id: 8,
    title: 'Retro Polaroid Instant Camera',
    description: 'Vintage analogue instant camera featuring dual lens autofocus system, creative double exposure mode, self-timer, and rechargeable battery.',
    price: 99.00,
    original_price: 119.00,
    category_id: 5,
    category_name: 'Accessories',
    category_slug: 'accessories',
    stock: 10,
    rating: 4.7,
    review_count: 164,
    image_url: 'https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=600&auto=format&fit=crop&q=80',
    badge: 'Trending',
    features: ['Autofocus System', 'Built-in Flash', 'Self-Timer Function', 'USB Rechargeable']
  }
];

export const INITIAL_ORDERS = [
  {
    id: 101,
    order_code: 'ORD-A8B9C1',
    customer_name: 'Alex Johnson',
    customer_email: 'alex@example.com',
    shipping_address: '123 Tech Boulevard, San Francisco, CA 94107',
    subtotal: 199.99,
    discount: 20.00,
    tax: 14.40,
    total_amount: 194.39,
    status: 'Completed',
    created_at: '2026-08-07T14:32:00Z'
  },
  {
    id: 102,
    order_code: 'ORD-F4E3D2',
    customer_name: 'Sophia Patel',
    customer_email: 'sophia@example.com',
    shipping_address: '456 Innovation Way, Austin, TX 78701',
    subtotal: 149.50,
    discount: 0.00,
    tax: 11.96,
    total_amount: 161.46,
    status: 'Processing',
    created_at: '2026-08-08T09:15:00Z'
  }
];
