export const INITIAL_CATEGORIES = [
  { id: 1, name: 'Mobiles & Smartphones', slug: 'mobiles' },
  { id: 2, name: 'Electronics', slug: 'electronics' },
  { id: 3, name: 'Audio', slug: 'audio' },
  { id: 4, name: 'Fashion', slug: 'fashion' },
  { id: 5, name: 'Home & Living', slug: 'home-living' },
  { id: 6, name: 'Accessories', slug: 'accessories' }
];

export const INITIAL_PRODUCTS = [
  {
    id: 1,
    title: 'Apple iPhone 15 Pro Max (256 GB) - Natural Titanium',
    description: 'Forged in titanium with A17 Pro chip, customizable Action button, 48MP main camera system with 5x Telephoto optical zoom, and Super Retina XDR display.',
    price: 149900,
    original_price: 159900,
    category_id: 1,
    category_name: 'Mobiles & Smartphones',
    category_slug: 'mobiles',
    stock: 12,
    rating: 4.9,
    review_count: 342,
    image_url: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=600&auto=format&fit=crop&q=80',
    badge: 'Flipkart Choice',
    features: ['Titanium Design', 'A17 Pro Chip', '48MP Pro Camera System', 'USB-C with USB 3 Speeds']
  },
  {
    id: 2,
    title: 'Samsung Galaxy S24 Ultra 5G (Titanium Gray, 12GB, 512GB)',
    description: 'Galaxy AI is here. 200MP camera with AI Zoom, built-in S Pen, Snapdragon 8 Gen 3 for Galaxy, and quad HD+ Dynamic AMOLED 2X display.',
    price: 129999,
    original_price: 139999,
    category_id: 1,
    category_name: 'Mobiles & Smartphones',
    category_slug: 'mobiles',
    stock: 15,
    rating: 4.8,
    review_count: 289,
    image_url: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=600&auto=format&fit=crop&q=80',
    badge: 'Amazon Bestseller',
    features: ['200MP Quad Camera', 'Built-in S Pen', 'Galaxy AI Features', '5000mAh Battery']
  },
  {
    id: 3,
    title: 'OnePlus 12 5G (Silky Black, 16GB RAM, 512GB Storage)',
    description: 'Powered by Snapdragon 8 Gen 3, 4th Gen Hasselblad Camera System for Mobile, 120Hz ProXDR display with LTPO 3.0, and 100W SUPERVOOC fast charging.',
    price: 64999,
    original_price: 69999,
    category_id: 1,
    category_name: 'Mobiles & Smartphones',
    category_slug: 'mobiles',
    stock: 20,
    rating: 4.7,
    review_count: 198,
    image_url: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=600&auto=format&fit=crop&q=80',
    badge: 'Top Rated',
    features: ['Snapdragon 8 Gen 3', 'Hasselblad Camera', '100W SuperVOOC', '5400mAh Battery']
  },
  {
    id: 4,
    title: 'Xiaomi Redmi Note 13 Pro+ 5G (Fusion Purple, 12GB, 512GB)',
    description: '200MP OIS camera, 3D Curved AMOLED 120Hz display, IP68 dust & water resistance, MediaTek Dimensity 7200-Ultra, and 120W HyperCharge.',
    price: 31999,
    original_price: 35999,
    category_id: 1,
    category_name: 'Mobiles & Smartphones',
    category_slug: 'mobiles',
    stock: 25,
    rating: 4.6,
    review_count: 420,
    image_url: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600&auto=format&fit=crop&q=80',
    badge: 'Hot Deal',
    features: ['200MP OIS Camera', '120W HyperCharge', 'IP68 Water Resistant', '3D Curved AMOLED']
  },
  {
    id: 5,
    title: 'Realme GT 6 5G (Fluid Silver, 12GB RAM, 256GB Storage)',
    description: 'World’s brightest 6000 nits Ultra Bright Display, Snapdragon 8s Gen 3 flagship processor, 50MP Sony LYT-808 OIS main camera, and 120W SuperVOOC charging.',
    price: 40999,
    original_price: 44999,
    category_id: 1,
    category_name: 'Mobiles & Smartphones',
    category_slug: 'mobiles',
    stock: 18,
    rating: 4.7,
    review_count: 165,
    image_url: 'https://images.unsplash.com/photo-1565849904461-04a58ad377e0?w=600&auto=format&fit=crop&q=80',
    badge: 'Trending',
    features: ['6000 Nits Brightness', 'Snapdragon 8s Gen 3', 'Sony LYT-808 Camera', '120W Fast Charge']
  },
  {
    id: 6,
    title: 'Aura ANC Wireless Headphones',
    description: 'Studio-quality wireless over-ear headphones with active noise cancellation, 40-hour battery life, and ultra-soft memory foam ear cushions.',
    price: 14999,
    original_price: 19999,
    category_id: 3,
    category_name: 'Audio',
    category_slug: 'audio',
    stock: 14,
    rating: 4.8,
    review_count: 142,
    image_url: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&auto=format&fit=crop&q=80',
    badge: 'Best Seller',
    features: ['Active Noise Cancellation', '40h Battery Life', 'Bluetooth 5.3', 'Fast USB-C Charging']
  },
  {
    id: 7,
    title: 'Minimalist Leather Smart Watch',
    description: 'Sleek smartwatch featuring an AMOLED display, heart rate tracking, sleep monitoring, and a premium genuine Italian leather strap.',
    price: 9999,
    original_price: 12999,
    category_id: 2,
    category_name: 'Electronics',
    category_slug: 'electronics',
    stock: 10,
    rating: 4.6,
    review_count: 89,
    image_url: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&auto=format&fit=crop&q=80',
    badge: 'Popular',
    features: ['AMOLED Touchscreen', 'Heart Rate & SpO2', '5 ATM Water Resistance', '7-Day Battery']
  },
  {
    id: 8,
    title: 'Ergonomic Mechanical Keyboard',
    description: 'Compact 75% hot-swappable RGB mechanical keyboard with custom lubricated switches and acoustic dampening foam.',
    price: 8999,
    original_price: 10999,
    category_id: 2,
    category_name: 'Electronics',
    category_slug: 'electronics',
    stock: 8,
    rating: 4.9,
    review_count: 210,
    image_url: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600&auto=format&fit=crop&q=80',
    badge: 'Top Rated',
    features: ['Hot-Swappable PCB', 'South-Facing Per-Key RGB', 'PBT Double-shot Keycaps', 'Triple-Mode Connectivity']
  }
];

export const INITIAL_ORDERS = [
  {
    id: 101,
    order_code: 'ORD-IN8B9C',
    customer_name: 'Sridhar Palivela',
    customer_email: 'sridhar@example.com',
    shipping_address: 'Flat 402, Cyber Towers Road, Madhapur, Hyderabad, Telangana 500081',
    subtotal: 149900,
    discount: 14990,
    tax: 10792,
    total_amount: 145702,
    status: 'Completed',
    created_at: '2026-08-07T14:32:00Z'
  }
];
